### ISSUE TITLE
Fix basic typos on website and readme, add gitignore and codeofconduct.md 

### ISSUE THREAD

**Issue by CYCLOP5** [techcsispit/3DPortfolio#3]

**Comment by CYCLOP5** [comment]
#2

**Comment by techcsispit** [comment]
Can you elaborate about the Issue and how it affects the project?

**Comment by CYCLOP5** [comment]
- Basic documentation changes in readme and addition of Code of conduct.md as referenced in endpart of readme.

- Typos and grammar fixed on the webpage.(past tense is now used in past work)

**Comment by techcsispit** [comment]
Thank You For your contributions
